### ISSUE TITLE
Trying to create a new custom page

### ISSUE THREAD

**Issue by danimontanaro** [GatsbyStorefront/gatsby-theme-storefront-shopify#10]
### What happened:
I am trying to create a custom page for my E-commerce. To do that, I created the`/pages` folder and inside that the `Thanks.jsx` file to define the page component (like making "shadowing" of the pages folder but I am not sure that this is "shadowing"). However, when I run the project, the page doesn't exist and it shows me this error in the console: 

![image](https://user-images.githubusercontent.com/22395442/80131419-98866f80-8570-11ea-9481-aff6df0c2745.png)

### Reproduction:
You can check our code here: 
https://github.com/davidpaley/gatsby-ecommerce/pull/4/files

This is the PR for the change in our public repo.

If there is any workaround, please let me know.

**Comment by paveli** [comment]
Hi @danimontanaro,
If you just want to add a page to your store, there is no need to use shadowing and make changes in the theme.
Just create `/src/pages` folder and place your `thanks.js` file there.
