### ISSUE TITLE
broken queries on initial build

### ISSUE THREAD

**Issue by twilightscapes** [GatsbyStorefront/gatsby-theme-storefront-shopify#13]
I've followed the install and everything seems to go okay. I see the connection to Shopify worked and it imported products, etc... but at the last section, it throws errors:

Cannot query field "image" on type "ShopifyCollection".

Cannot query field "altText" on type "ShopifyProductImages".

Cannot query field "compareAtPrice" on type "ShopifyProductVariant".

**Comment by twilightscapes** [comment]
Sorry, I worked through the errors and realized my products were missing these items. I supplied dummy items and it built just fine. Thanks!

**Comment by bikeidaho** [comment]
> Sorry, I worked through the errors and realized my products were missing these items. I supplied dummy items and it built just fine. Thanks!

I wanted to thank OP for the public PEBKAC. This quickly confirmed my suspicions and allowed me to move to the next issue. Thanks!
