### ISSUE TITLE
add breadcrumps

### ISSUE THREAD

**Issue by muescha** [GatsbyStorefront/gatsby-theme-storefront-shopify#2]
**Describe the feature you'd like:**

when i am in a deep subcategory i can go only back with the "hamburger menu" to the topmost category

**Suggested implementation:**

add a breadcrump element or a link to the next higher category, that the user can navigate better.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by paveli** [comment]
Hi @muescha 
This is a good one! 
Think it is enough to have a straightforward implementation using `gatsbystorefront-config.js` and it's `menu` object as data source to create breadcrumbs.

**Comment by n8tb1t** [comment]
This starter is awesome!
