### ISSUE TITLE
Doesn't seem to be working with Gatsby 3.1.1

### ISSUE THREAD

**Issue by Wilddata** [GatsbyStorefront/gatsby-theme-storefront-shopify#21]
Any help would be great.
I also tried to install it with the --force flag but nothing compile

`npm install @gatsbystorefront/gatsby-theme-storefront-shopify  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-default@0.1.0
npm ERR! Found: gatsby@3.1.2
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^3.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.13.38" from @gatsbystorefront/gatsby-theme-storefront-shopify@4.0.0
npm ERR! node_modules/@gatsbystorefront/gatsby-theme-storefront-shopify
npm ERR!   @gatsbystorefront/gatsby-theme-storefront-shopify@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps`

**Comment by paveli** [comment]
You are dealing with dependencies conflict. Gatsby Storefront v4.0.0 requires gatsby v2.

Currently we are testing the new version of Gatsby Storefront with gatsby v3 and hope to release it soon.

Meanwhile try to resolve the dependencies conflict.

**Comment by paveli** [comment]
This branch contains necessary updates for Gatsby Storefront to work with Gatsby v3.
https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify/tree/v5
