### ISSUE TITLE
Can't build project properly

### ISSUE THREAD

**Issue by chanmathew** [GatsbyStorefront/gatsby-theme-storefront-shopify#3]
Hey guys,

When I follow the instructions to setup the project I keep running into this error:
`Cannot query field "allShopifyShopPolicy" on type "Query"`

I also don't see any layout or theme files, are the setup instructions outdated?

Here's the steps I took:
`gatsby new store gatsbystorefront/gatsby-starter-storefront-shopify`
`cd store`
`npm install @gatsbystorefront/gatsby-theme-storefront-shopify`
Setup the env config.
Made sure the theme was enabled in the plugins.

However when I run `gatsby develop` it fails with that error message, and also I don't see any theme files?

**Comment by paveli** [comment]
Hi @chanmathew ,

- Just run `npm install` in `gatsby-starter-storefront-shopify` dir. This will install all the dependencies. 
- In your Shopify store add Policies (https://help.shopify.com/en/manual/checkout-settings/refund-privacy-tos)

**Comment by paveli** [comment]
@chanmathew to modify theme you need to use shadowing (https://www.gatsbyjs.org/docs/themes/shadowing/). See the theme files [here](https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify/tree/master/src) and use shadowing to override what you need to.

**Comment by paveli** [comment]
@all-contributors please add @paveli for code, design, doc, example, ideas
