### ISSUE TITLE
Make article/blog and pages optional

### ISSUE THREAD

**Issue by mimibar** [GatsbyStorefront/gatsby-theme-storefront-shopify#5]
**Describe the feature you'd like:**
The g**atsby-theme-storefront-shopify** is not compatible with the [Shopify Lite plan](https://www.shopify.com/lite). The Shopify Lite plan does not provide an online store, therefore no blog posts or store policies can be created.
<img width="999" alt="image" src="https://user-images.githubusercontent.com/2718783/76156593-217d4080-60c2-11ea-9f7e-951b72a97516.png">

**Suggested implementation:**
Verify that `allShopifyArticle` and `allShopifyBlog` exist before querying it.

If there is any workaround, please let me know.

**Comment by paveli** [comment]
@mimibar Hi, can you please provide full build log (`gatsby develop` command output)? 
Can you provide SHOPIFY_ACCESS_TOKEN (from `.env` file) for testing? (you can email me)

**Comment by paveli** [comment]
@mimibar since I don't have a store on Lite plan for testing.

**Comment by mimibar** [comment]
Thanks for your prompt reply! Here is the full `gatsby develop log`. An I have created an access token that I sent to your email.

[develop.log](https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify/files/4308050/develop.log)

**Comment by paveli** [comment]
@mimibar Please check this (607a1ef) branch for the quick fix.
Please report any issues. I will merge it to master if everything works fine.

**Comment by mimibar** [comment]
Thanks Pavel for the speedy fix! I think it works good, much better than me commenting it out directly in the code. 

I just need to work now on the shadowing to replace my index page with the main page and my configuration.

**Comment by paveli** [comment]
I will leave a quick note here that in order to ease theme configuration in the next version it will be moved to `gatsby-config.js`.  Please see [v2 branch](https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify/tree/v2).

**Comment by mimibar** [comment]
Hi Pavel!

I pulled the latest changes but after the v2 refactoring
<https://github.com/GatsbyStorefront/gatsby-theme-storefront-shopify/commit/078235fb9b1af0005a19188a4d896ee442dd2529>
it fails. During exports.sourceNodes, isShopifyLite is false, so when it
gets to exports.createPages the dummy types Blog, Articles are not there.

However, since sourceNodes is before run it creates initial GraphQL schema
in the Gatbsy bootstrap sequence, shopifyLite cannot be queried with
graphql.
I thought about also moving this createTypes call to
createSchemaCustomization
<https://www.gatsbyjs.org/docs/node-apis/#createSchemaCustomization>, but
still, this is before the schema generation.

Do you have a chance to take a look?

Thanks!

-Miriam
