### ISSUE TITLE
Shadowing templates folder.results in multiple query errors.

### ISSUE THREAD

**Issue by danielclough** [GatsbyStorefront/gatsby-theme-storefront-shopify#9]
I am having difficulty shadowing the templates folder.
The error is related to duplication of queries. I have not the same problem with other themes.

To duplicate the error just shadow the template folder.

I think it's related to issue.

https://github.com/gatsbyjs/gatsby/pull/17681
"the documents for createPage tells you to use an absolute path to the component. So, the theme author didn't do anything wrong. (per docs) The component will always have an extension, so the algorithm resolving the shadowed component will not allow extension overriding."

**Comment by paveli** [comment]
Hi @danielclough 
There are opened issues for this bug, like: https://github.com/gatsbyjs/gatsby/issues/19980.
For now the way to overcome it is to rename the query in shadowed component.
Maybe we need to notice it in the docs and [shadowing example repo](https://github.com/GatsbyStorefront/theme-shadowing-example). PR's are welcome ;-)

**Comment by danielclough** [comment]
Thanks!
I discovered how to work around the problem.
I have not done any theme work in Gatsby, so I don't know where to start
with a PR - but if I find a solution I will try to implement it.
